# Generated by Django 5.2.8 on 2025-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0002_badge_notification_userpoints_userstreak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('common_sentences', 'Common Sentences'), ('featured', 'Featured Content'), ('quick_links', 'Quick Links')], default='common_sentences', max_length=50)),
                ('icon', models.CharField(choices=[('fa-comment-dots', 'Comment Dots'), ('fa-graduation-cap', 'Graduation Cap'), ('fa-briefcase', 'Briefcase'), ('fa-home', 'Home'), ('fa-heart', 'Heart'), ('fa-users', 'Users'), ('fa-book', 'Book'), ('fa-star', 'Star'), ('fa-music', 'Music'), ('fa-utensils', 'Food/Utensils'), ('fa-plane', 'Travel/Plane'), ('fa-hospital', 'Hospital/Medical'), ('fa-shopping-cart', 'Shopping'), ('fa-futbol', 'Sports'), ('fa-palette', 'Art/Palette'), ('fa-car', 'Car/Transport'), ('fa-phone', 'Phone'), ('fa-calendar', 'Calendar'), ('fa-clock', 'Clock/Time'), ('fa-map-marker-alt', 'Location')], default='fa-comment-dots', max_length=30)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('teal', 'Teal'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink')], default='blue', max_length=20)),
                ('link', models.CharField(help_text='URL or path (e.g., /lessons/?category=daily)', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Card',
                'verbose_name_plural': 'Featured Cards',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
