# Generated by Django 5.2.8 on 2025-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0003_featuredcard_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcard',
            name='description',
            field=models.CharField(blank=True, help_text='Short description (optional)', max_length=200),
        ),
    ]
