# Generated by Django 5.2.8 on 2025-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0004_add_featuredcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
