# Generated by Django 5.2.8 on 2025-12-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0005_fix_notification_link_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('badge', 'Badge Earned'), ('level_up', 'Level Up'), ('streak', 'Streak Milestone'), ('achievement', 'Achievement'), ('reminder', 'Learning Reminder'), ('system', 'System Notification')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20),
        ),
    ]
