# Generated by Django 5.2.8 on 2025-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0006_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after quiz (why this answer is correct/incorrect)'),
        ),
    ]
