# Generated by Django 5.2.8 on 2025-12-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0007_add_answer_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='freeze_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='freeze_last_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='freeze_used_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
