# Generated by Django 5.2.8 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0009_add_vocabulary_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Teachers can access the management panel'),
        ),
    ]
