# Generated by Django 5.2.8 on 2026-01-04 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang', '0010_add_is_teacher_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='signlang_qu_user_id_15b2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='signlang_qu_user_id_100a76_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'status'], name='signlang_us_user_id_a536af_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', '-last_accessed'], name='signlang_us_user_id_5c8dc6_idx'),
        ),
    ]
